spring.application.name=ExpenseTracker
server.port=8080
spring.jackson.time-zone=UTC

spring.datasource.url=jdbc:mariadb://localhost:3306/expensetracker
spring.datasource.username=expensetracker
spring.datasource.password=expensetracker
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=70
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.threads.virtual.enabled=true