spring.application.name=ExpenseTracker
spring.config.import=optional:file:.env[.properties]
server.port=8080

spring.jackson.time-zone=UTC
spring.jackson.mapper.accept-case-insensitive-properties=true

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=70
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.threads.virtual.enabled=true

app.security.jwt.secret-key=${JWT_SECRET:8OnMwU91F8/rWb/AWvjd2UN5TxFcrpQFlPVzZNPDhiQ9l7W14WTdfeGx9c/Phv1mgHJDFqAyRQgFuDV1YEbRjQ==}
app.security.jwt.expiration-ms=${JWT_EXPIRATION:86400000}

app.security.cors.allowed-origins[0]=http://localhost
app.security.cors.allowed-origins[1]=http://127.0.0.1
app.security.cors.allowed-origins[2]=http://localhost:3000
app.security.cors.allowed-origins[3]=http://127.0.0.1:3000
app.security.cors.allowed-origins[4]=http://localhost:4200
app.security.cors.allowed-origins[5]=http://localhost:5173
app.security.cors.allowed-origins[6]=https://inventoryx.eu
app.security.cors.allowed-origins[7]=https://www.inventoryx.eu
app.security.cors.allowed-origins[8]=https://pizza-cipolla-storage-fe.vercel.app

app.security.cors.allowed-headers[0]=Authorization
app.security.cors.allowed-headers[1]=Content-Type
app.security.cors.allowed-headers[2]=Accept
app.security.cors.allowed-headers[3]=Origin

app.security.cors.allowed-methods[0]=GET
app.security.cors.allowed-methods[1]=POST
app.security.cors.allowed-methods[2]=PUT
app.security.cors.allowed-methods[3]=PATCH
app.security.cors.allowed-methods[4]=DELETE
app.security.cors.allowed-methods[5]=OPTIONS

app.security.default-admin.email=${DEFAULT_ADMIN_EMAIL:admin@admin.com}
app.security.default-admin.password=${DEFAULT_ADMIN_PASSWORD:admin}
app.security.default-admin.first-name=${DEFAULT_ADMIN_FIRST_NAME:System}
app.security.default-admin.last-name=${DEFAULT_ADMIN_LAST_NAME:Administrator}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:your-cloud-name}
cloudinary.api-key=${CLOUDINARY_API_KEY:your-api-key}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:your-api-secret}